[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.install]
# Railway ko bolein ke sirf backend folder mein jaye aur requirements install kare
cmds = ["cd rag-chatbot/backend && pip install -r requirements.txt"]

[start]
# Server start karne ka command
cmd = "cd rag-chatbot/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
