import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * This sidebar is automatically generated from the docs folder structure.
 */
const sidebars: SidebarsConfig = {
  textbook: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
